### ISSUE TITLE
URL routes are not using the npm style

### ISSUE THREAD

**Issue by d42ohpaz** [n4bb12/verdaccio-npm-urls#1]
#### Versions

|                    | Version |
| ------------------ | ------- |
| verdaccio          |   4.4.1     |
| verdaccio-npm-urls |   1.0.0      |

#### Expected behavior
Click on a package and have the URL in the address bar be the `/package/my-package` style of URL.

#### Observed behaviour
Address bar still shows V4 `/-/web/detail/my-package` style of URL.

#### Steps to reproduce
1. Install package
2. Configure package in Verdaccio config
3. Restart both verdaccio and httpd (for good measure)

#### Additional context
N/A

**Comment by n4bb12** [comment]
Maybe this is a misunderstanding. The plugin is not a reverse proxy, it only performs a redirect to a working URL.

If you go to `/package/my-package` you would usually get a  404. With the plugin you are redirected to Verdaccios package URL `/-/web/detail/my-package`.

This is useful when existing publishing tools print URLs that are meant to work with npm. With this plugin, you'll land on a working page. But the target URL is going to be Verdaccio's package URL.

Hope that helps?

**Comment by d42ohpaz** [comment]
Oh ok. That makes much more sense, and yes the way you describe it does work. Thank you!

**Comment by d42ohpaz** [comment]
PIBTKATC error. :)
